# -*- coding: utf-8 -*-
"""26_05_2023_4potok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n4YLWQY8dqcGvE5QjmVIws3pOEFfbNH7
"""

print("Привет мир")